GET http://localhost:3000/posts
Content-Type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGFsaGEiLCJpYXQiOjE3MTIzODc3MzB9.Iwu9GuFlN7ZYMj1y03qNbK_oIX1REHif1zOCQJKWT6Q"

{
    "name":"talha"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name":"talha"
}